apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-intel-deployment
  labels:
    app: nginx-multiarch
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      arch: intel
  template:
    metadata:
      labels:
        app: nginx-multiarch
        arch: intel
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-intel-svc
  namespace: nginx
spec:
  sessionAffinity: None
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-multiarch
    arch: intel
  type: LoadBalancer
