apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-intel-config
  namespace: nginx
data:
  nginx.conf: |
    worker_processes auto;
    worker_cpu_affinity auto;
    worker_rlimit_nofile 1000000;
    events {
        worker_connections 6144;
        use epoll;
        multi_accept on;
    }
    http {
        access_log off;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        server {
            listen 80;
            location / {
                return 200 '{"message":"nginx response","timestamp":"$time_iso8601","server":"$hostname","request_uri":"$request_uri"}';
                add_header Content-Type application/json;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-intel-deployment
  labels:
    app: nginx-multiarch
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      arch: intel
  template:
    metadata:
      labels:
        app: nginx-multiarch
        arch: intel
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-intel-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-intel-svc
  namespace: nginx
spec:
  sessionAffinity: None
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-multiarch
    arch: intel
  type: LoadBalancer
