apiVersion: v1
kind: Service
metadata:
  name: nginx-multiarch-svc
  namespace: nginx
spec:
  sessionAffinity: None
  ports:
  - nodePort: 30083
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-multiarch
  type: LoadBalancer
