apiVersion: v1
data:
  nginx.conf: |
    worker_processes 2;
    worker_cpu_affinity 01 10;
    worker_rlimit_nofile 1000000;
    events {
        worker_connections 6144;
        use epoll;
        multi_accept on;
    }
    http {
        access_log off;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        server {
            listen 80;
            location / {
                return 200 '{"message":"nginx response","timestamp":"$time_iso8601","server":"$hostname","request_uri":"$request_uri"}';
                add_header Content-Type application/json;
            }
        }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"nginx.conf":"worker_processes 2;\nworker_cpu_affinity 01 10;\nworker_rlimit_nofile 1000000;\nevents {\n    worker_connections 6144;\n    use epoll;\n    multi_accept on;\n}\nhttp {\n    access_log off;\n    sendfile on;\n    tcp_nopush on;\n    tcp_nodelay on;\n    keepalive_timeout 65;\n    server {\n        listen 80;\n        location / {\n            return 200 '{\"message\":\"nginx response\",\"timestamp\":\"$time_iso8601\",\"server\":\"$hostname\",\"request_uri\":\"$request_uri\"}';\n            add_header Content-Type application/json;\n        }\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-arm","namespace":"nginx"}}
  creationTimestamp: "2025-10-23T20:02:56Z"
  name: nginx-arm
  namespace: nginx
  resourceVersion: "446162"
  uid: 6c2fd24a-8a76-45d5-92df-3b2bc7239db8
